package io.mosip.registration.controller.device;

import org.springframework.stereotype.Controller;

import javafx.fxml.FXML;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;

@Controller
public class BiometricExceptionsController {
	
	@FXML
	private GridPane exceptionBiometricsPane;
	@FXML
	private Pane leftHandPane;
	@FXML
	private ImageView FINGERPRINT_SLAB_LEFT;
	@FXML
	private ImageView leftMiddle;
	@FXML
	private ImageView leftIndex;
	@FXML
	private ImageView leftRing;
	@FXML
	private ImageView leftLittle;
	@FXML
	private Pane rightHandPane;
	@FXML
	private ImageView FINGERPRINT_SLAB_RIGHT;
	@FXML
	private ImageView rightMiddle;
	@FXML
	private ImageView rightRing;
	@FXML
	private ImageView rightIndex;
	@FXML
	private ImageView rightLittle;
	@FXML
	private Pane thumbsPane;
	@FXML
	private ImageView FINGERPRINT_SLAB_THUMBS;
	@FXML
	private ImageView leftThumb;
	@FXML
	private ImageView rightThumb;
	@FXML
	private Pane irisPane;
	@FXML
	private ImageView IRIS_DOUBLE;
	@FXML
	private ImageView rightEye;
	@FXML
	private ImageView leftEye;

	// Event Listener on ImageView[#leftMiddle].onMouseClicked
	@FXML
	public void addException(MouseEvent event) {
		// TODO Autogenerated
	}
}
