CREATE TABLE "REG"."LOC_HIERARCHY_LIST"("HIERARCHY_LEVEL" INTEGER NOT NULL, "HIERARCHY_LEVEL_NAME" VARCHAR(36) NOT NULL, "LANG_CODE" VARCHAR(3) NOT NULL, "IS_ACTIVE" BOOLEAN NOT NULL, "CR_BY" VARCHAR(256) NOT NULL, "CR_DTIMES" TIMESTAMP NOT NULL, "UPD_BY" VARCHAR(256), "UPD_DTIMES" TIMESTAMP);

ALTER TABLE "REG"."LOC_HIERARCHY_LIST" ADD CONSTRAINT "PK_LOCHL_ID" PRIMARY KEY ("HIERARCHY_LEVEL", "HIERARCHY_LEVEL_NAME", "LANG_CODE" );
