apiVersion: v2
name: regproc-group2
description: A Helm chart for MOSIP Registration Processor Group 2 stage
type: application
version: 12.1.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - regproc-group2
  - regproc
maintainers:
  - email: info@mosip.io
    name: MOSIP
