\c mosip_regprc 

GRANT CONNECT
   ON DATABASE mosip_regprc
   TO regprcuser;

GRANT USAGE
   ON SCHEMA regprc
   TO regprcuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA regprc
   TO regprcuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA regprc 
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO regprcuser;

